# Generated by Django 5.0.4 on 2024-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
