# Generated by Django 5.0.4 on 2024-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapps', '0002_remove_hotel_amenities_remove_hotel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
