# Generated by Django 5.0.4 on 2024-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapps', '0003_alter_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
